name: update

on:
  # Run at 12am UTC every Monday
  schedule:
    - cron: "0 0 * * 1" 
  
  # Allow to manually run the job at any time
  workflow_dispatch:

jobs:
  waka:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          COMMIT_MESSAGE: "🚀✨ Updated with Dev Metrics"
          COMMIT_USERNAME: "metrics-bot"
          SHOW_UPDATED_DATE: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Update README
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          USER: "2972717719499816"
        run: |-
          python build.py
          cat README.md
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "1052785899@qq.com"
          git config --global user.name "Love-YY-bot"
          git pull
          git add -A
          git commit -m "Updated profile page" || exit 0
          git push