name: Update README

on:
  # Run at 12am UTC
  schedule:
    - cron: "0 0 * * *" 
  
  # Allow to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push on the master branch
  push:
    branches:
      - master

jobs:
  waka:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SYMBOL_VERSION: 2

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repo
  #       uses: actions/checkout@v3
  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.8
  #     - uses: actions/cache@v2
  #       name: Configure pip caching
  #       with:
  #         path: ~/.cache/pip
  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pip-
  #     - name: Install Python dependencies
  #       run: |
  #         python -m pip install -r requirements.txt
  #     - name: Update README
  #       env:
  #         GH_TOKEN: ${{secrets.ACCESS_TOKEN}}
  #       run: |-
  #         python build.py
  #         cat README.md
  #     - name: Commit and push if changed
  #       run: |-
  #         git diff
  #         git config --global user.email "1052785899@qq.com"
  #         git config --global user.name "Love-YY-bot"
  #         git pull
  #         git add -A
  #         git commit -m "Updated profile page" || exit 0
  #         git push